### ISSUE TITLE
Submit baseline updates for CISA review and approval

### ISSUE THREAD

**Issue by mitchelbaker-cisa** [cisagov/ScubaGear#1046]
# 💡 Summary #

As part of the new continuous baseline update process, we will have to submit Word documents which reflect any additions/revisions/deletions to the baselines.

**Planned baseline updates for ScubaGear v1.2.0:**

1. Power BI

- [ ] Add missing information note to PowerBI baseline (No policy change, just consistency fix in intro). ([PR #907](https://github.com/cisagov/ScubaGear/pull/907))

2. AAD

- [x] Modify Azure AD baseline implementation instructions to include PIM for Groups. ([PR #926](https://github.com/cisagov/ScubaGear/pull/926))
- [x] Update MS.AAD.5.3v1.0 and MS.AAD.5.4v1.0 instructions to match correct buttonology ([PR #1028](https://github.com/cisagov/ScubaGear/pull/1028))

3. EXO 
- [x] Revise MS.EXO.5.1v1.0 to remove exceptional note ([PR #939](https://github.com/cisagov/ScubaGear/pull/939)) 

## Motivation and context ##

Get CISA approval of latest baseline updates for Glacier release. 

## Implementation notes ##

Please provide details for implementation, such as:

- For each new update, it must be highlighted with a comment. For each comment it must be labeled with “Web Content Update” and a simple description of the update. 

![baseline-revision-example-1](https://github.com/cisagov/ScubaGear/assets/149098823/eab0d952-16ff-4a0e-98ae-3b2505ac2265)

## Acceptance criteria ##

How do we know when this work is done?

- [x] Word document versions are updated with comments for each new baseline update
- [x] Documents are forwarded to PMSS to prepare for CISA review
- [ ] Track duration of each review step to improve future iterations for conducting baseline review

**Comment by ahuynhMITRE** [comment]
PowerBI documents updates are directed only to the markdown version. The update included adding in the TLP indicators that were originally missed in the markdown versions, this update is not applicable to the word versions submitted on 04/05 to CISA and PMSS to push through the publication process.

**Comment by ahuynhMITRE** [comment]
> @ahuynhMITRE Based on the approval, can we close this out?

yep good call, thanks for the reminder addam!
