### ISSUE TITLE
Accessibility improvements to HTML reports 

### ISSUE THREAD

**Issue by mitchelbaker-cisa** [cisagov/ScubaGear#1061]
# Description #

This epic focuses on making accessibility improvements to ScubaGear HTML reports. New issues were added to cover various use cases around navigating the tool with a screen reader when the reports were tested for 508/WCAG 2.2 compliance.

## Initiative / Goal ##

Address follow-up issues created from the previous epic, #820. 

## Acceptance criteria ##

How do we know when this work is done?

- [ ] New tests have been built or existing tests have been modified to validate HTML report changes work/look as intended
- [ ] Text content in HTML reports can be read by screen readers and functionality tied to inputs, links, and buttons are clear 
- [ ] Expand/collapse functionality in the CAP table can be reached with the tab key 

## Stakeholders / Resources ## 

Include CISA decision makers and dev team members in discussions about this epic. Resources needed for this epic include access to GitHub actions marketplace and ability to create new issue templates.

## Timeline ##
The current projected timeline for delivery of this epic feature is with the associated release milestone.

## Associated Tasks ##
See details in the following issues:

- [x] #961
- [x] #972 
- [x] #1047
