### ISSUE TITLE
Baseline Policy Enhancements, Part 1

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1071]
# 💡 Summary #

Several SCuBA M365 baseline policy updates and additions are in the process of being reviewed, developed, and made.  This epic ensures that baseline changes are coordinated for internal consistency.  Small baseline changes will be made during this epic, while more complex changes will have recommendations agreed upon for future implementation in another epic (Part 2).

## Motivation and context ##

Baseline changes are necessary to keep pace with changing services and evolving guidance.

## Implementation notes ##

Please provide details for implementation, such as:

- Developers review each issue for fix or enhancement against current baseline
- Perform testing necessary to validate behavior and understand settings
- Make recommendation to group for policy updates or changes
- Create updates and issue PR for review of small changes

## Acceptance criteria ##

The following issues are completed

- [x] Successfully created discontinued policies template in markdown #1016
- [x] MITRE ATT&CK mappings added to baselines #937 
- [x] Additional baseline change recommendations have been agreed to by the product owner
