### ISSUE TITLE
Baseline Policy Enhancements, Part 2

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1085]
# 💡 Summary #

Several SCuBA M365 baseline policy updates and additions are in the process of being reviewed, developed, and made.  This epic ensures that baseline changes are coordinated for internal consistency.  The work was split into two epics.  The first made small, easy to make changes and worked on investigating and determining approaches for complex baseline changes.  This epic focuses on implementing the more complex changes.

## Motivation and context ##

Baseline changes are necessary to keep pace with changing services and evolving guidance.

## Implementation notes ##

Please provide details for implementation, such as:

- Review recommendations and findings from baseline policy investigation epic (Part 1)
- Create updates from recommendations and issue PR for review
- Make additional changes to update/add associated assessment checks
- Issue PR for review of assessment check updates
- Test changes to policy with new assessment tests

## Acceptance criteria ##

The following issues are completed

- [x] Entra/Azure AD baseline successfully updated #921
- [x] SPF policy items in Exchange Online baseline have been reviewed and revised #900
- [x] Circular references in baselines have been successfully resolved
- [x] Mix of SHALL/SHOULD policies in Exchange baseline have been resolved #524
