### ISSUE TITLE
Centralize constant values to single location

### ISSUE THREAD

**Issue by james-garriss** [cisagov/ScubaGear#1136]
# 💡 Summary #

ScubaGear code has a tendency to repeat values that should be listed once and to bury values in code that should be easily configurable .  These values should be extracted into a constants file, where they can be found, set, and used by any developer.

## Motivation and context ##

Creating a single location for recurring values makes maintenance of those values easier.

## Implementation notes ##

Please provide details for implementation, such as:

- Identify repeated values throughout the code and documentation
- Define a common location and means of reference
- Update dependencies to use referenced location rather than repeating values

## Acceptance criteria ##

The following issues are completed

- [ ] #869 - Repeated product names
- [ ] #1088 - Modules to install and uninstall
- [ ] #1140 - Required dependencies (PowerShell, OPA, etc.)
- [ ] #190 - Clean up the parameter battlefield
- [ ] #47 - Update README to include list of Required Min/Max PowerShell Module versions.

**Comment by FollyBeachGurl** [comment]
During refinement team decided to move this issue to a low priority and keep in the backlog
