### ISSUE TITLE
Ensure robust escape handling for ScubaGear inputs

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1138]
# 💡 Summary #

Several reports of ScubaGear erroring out have been received and the common thread appears to be tenants that contain escaped values or '\' characters, such as in file paths, within various tenant fields (e.g. policy names).  The goal is to investigate and develop a solution to address the general escaping issue rather than patch specific reported instances.

## Motivation and context ##

Escaped values exist in the wild and need to be handled properly by ScubaGear.

## Implementation notes ##

Please provide details for implementation, such as:

- Review existing bug reports of escape handling issues and existing analyses
- Research options to resolve more generally
- Implement fix and test against existing bug reports

## Acceptance criteria ##

The following issues are completed

- [x] Escaped values are successfully handled and rendered by ScubaGear
- [ ] Issue #990 is resolved
- [ ] Issue #935 is resolved
- [ ] Issue #1214 is resolved
- [ ] Issue #1242 is resolved

**Comment by mitchelbaker-cisa** [comment]
[Potential implementation steps](https://github.com/cisagov/ScubaGear/issues/935#issuecomment-2015885713) from a user who encountered the escape handling error.

**Comment by gdasher** [comment]
I looked into this a little more closely as I had a few minutes and it was interesting.  OPA appears to use native golang JSON marshall/unmarshall on the input object.  Golang [claims ](https://pkg.go.dev/encoding/json)to implement RFC 7159, which does [specify ](https://www.rfc-editor.org/rfc/rfc7159.html )that "\" is a special character that may be used to represent unique code points in liu of encoding them directly in the byte string as utf8 (which also appears to be allowed).

ConvertTo-Json in a simple case in PS5 does properly escape:

`PS C:\Users\GRANT.DASHER> convertto-json -InputObject @{'abc' = 'flowers\abc'}
{
    "abc":  "flowers\\abc"
}`

There is a related [issue](https://github.com/PowerShell/PowerShell/issues/7693) about behavior differences in PS6+.

Whomever investigates this will need to understand the circumstances under which ConvertTo-Json is not creating the proper escaping and identify whether we can craft a general workaround.
