### ISSUE TITLE
Teams: identify changes to baseline to include meeting participant admission defaults

### ISSUE THREAD

**Issue by rmoffitt-m** [cisagov/ScubaGear#1339]
# 💡 Summary #

Update baselines to include [Microsoft Feature 392836](https://www.microsoft.com/en-us/microsoft-365/roadmap?rtc=1%26filters=&searchterms=392836). This feature adds organizer and co-organizer roles to Teams meetings, separating the ability to admit attendees and present content.

A more secure default would be to only allow meeting organizers and co-organizers to admit participants.

## Motivation and context ##

For all new meetings, the organizers will have access to set meeting admission options during scheduling time.
The default for this new meeting option can be configured by the tenant admins using the meeting
policy:

![image](https://github.com/user-attachments/assets/85516f92-6fbb-43e2-8357-8b1ab4d0a074)

The default option is to allow all presenters (e.g. tenant users) to admit external participants.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Validate new organizer lobby admission setting
- [ ] Document recommended change to Teams baseline with baseline change
- [ ] Issues created for implementation of changes as needed

**Comment by ahuynhMITRE** [comment]
@nanda-katikaneni is this issue still expect to have baseline changes and if yes what is the expected date to have these changes into a PR and reviewed?

**Comment by nanda-katikaneni** [comment]
Based on discussion with team during one of recent standups - it was thought that this does not require a change to existing baseline (restricting meeting participant admission to only organizers is thought to be too restrictive). No baseline/code changes - issue can be closed.
