### ISSUE TITLE
Future Check list for Sharepoint & OneDrive

### ISSUE THREAD

**Issue by Dylan-MITRE** [cisagov/ScubaGear#137]
# 💡 Summary #

Investigation Checklist for Sharepoint and OneDrive

## Motivation and context ##

Discovered some potential fix and issue for Sharepoint & OneDrive

This would be useful because it will improve Sharepoint and OneDrive report accuracy 

## Implementation notes ##

Check list 

- [ ] Combine policies if it is asking to check box and enter an expiration day. 
- [ ] Baseline update
- [ ] how the policy settings affect Sharepoint versus OneDrive separately
- [ ] test configuring the settings via the Sharepoint Admin center GUI and via the Powershell Cmdlets
- [ ] Identify dependencies between baseline policies
- [ ] Identify the correct configuration setting field for each baseline policy (All)
- [ ] Sharepoint has two levels of configuration settings, the Organization level and the specific Site level (Sharepoint 2.3)
- [ ] OneDrive 2.1 - OneDriveLoopSharingCapability
- [ ] OneDrive 2.2 - combine policies/ OneDriveLoopSharingCapability if 2.1 needed to be changed / <30 days
- [ ] OneDrive 2.3 - OneDriveLoopSharingCapability if 2.1 needed to be changed
- [ ] OneDrive 2.4 - N/A
- [ ] OneDrive 2.5 - N/A
- [ ] OneDrive 2.6 - implementation 
- [ ] OneDrive 2.7 - implementation
- [ ] Sharepoint 2.1 - N/A
- [ ] Sharepoint 2.2 - SharingCapability
- [ ] Sharepoint 2.3 - implementation for specific SharePoint sites
- [ ] Sharepoint 2.4 - combine policies/ <30 days
- [ ] Sharepoint 2.5 - implementation

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Investigate all items in the check list
- [ ] Create new issue if necessary during research

**Comment by Dylan-MITRE** [comment]
I think most are resolved since the merge and the unresolved ones already have tickets created. So my vote is to close. what do you think @tkol2022?

**Comment by tkol2022** [comment]
Thanks all. I don't think we performed all of the work described here but it has been so long since its inception that I forgot the detailed context behind it. Go ahead and close it. Happy Thanksgiving !
