### ISSUE TITLE
Configuration file code improvements

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1456]
# Description #

This epic is a larger feature to enhance the existing configuration file by improving error handling capabilities when running with a specified config file.

## Initiative / Goal ##

The goal is to improve ScubaGear operation when using a configuration file.  Specifically, to provide better handling in error use cases and provide better feedback to the user when it occurs.

## Relevant Issues

- [x] #1218
- [x] #1353
- [ ] #1437

## Hypothesis ##
By improving the evaluation of the configuration file and its parameters, ScubaGear users will have an easier time using more advanced options supported by the config file.  Additionally, better feedback to users when an error occurs will help them adjust any errors in the configuration quickly and easily.

## Acceptance criteria ##

Criteria that are considered must have for feature launch and in-scope for this epic include:

- [ ] Config file errors prevent further execution of ScubaGear to prevent undesired execution settings
- [ ] Error messages produced due to a configuration file issue provide clear and direct feedback to users
- [ ] Parameters passed via config file are evaluated and checked the same as those provided on the command line

## Stakeholders / Resources ##
Include CISA decision makers and dev team members in discussions about this epic.  Resources needed for this epic include access to test tenants and possibly ability to temporarily modify privileged roles for testing purposes.

## Timeline ##
The current projected timeline for delivery of this epic feature is with the associated release milestone.
