### ISSUE TITLE
Adjudicate SharePoint comments on the comment matrix

### ISSUE THREAD

**Issue by ahuynhMITRE** [cisagov/ScubaGear#240]
- [x] Send out link to Comments Matrix to the Baseline POCs
- [x] Andrew to schedule meetings with Baseline POCs
- [x] Internally review (Andrew & Baseline POCs) SharePoint Online comments from the comments matrix 
Purpose:
   1. Walkthrough comments with the baseline POCs to provide context
   2. Determine if additional follow-up with the original commenter is needed
- [x] Review comments with CISA to do the following:
   1. Prioritization of all comments reviewed 
   2. Creation of GitHub issues for the critical/high priority items into the backlog for further refinement
- [x] Refinement of created GitHub Issues into release lifecycle

**Comment by Sloane4** [comment]
- [x] Comment 26 - 2.3.1 Cannot go less restrictive than tenant level #288 
- [x] Comment 27 - 2.5.1 Instruction to reach "SharePoint Classic Admin Center" #289
- [x] Comment 44 - 2.7 blocking legacy authentication is duplicative of AAD #290
- [x] Comment 45 - Continuation of 44, should it be added to SharePoint as it is only in OneDrive #290
- [x] Comment 46 - 2.4.4 does not limit external sharing, fix implementation to be accurate #298
- [x] Comment 47 - 2.3.4 Directions are not correct "After selecting the site name, I don't see an option to Add domains" #297
- [x] Comment 48 - 2.4.4 Find what policies are missing the step that directs the user to save the configuration #301
- [x] Comment 50 - 2.2 Policy bullet is missing the statement “External Sharing SHOULD be Set to New and Existing Guests” #302
- [x] Comment 51 - 2.2 make sure the use of and/or is consistent in each policy #304
- [x] Comment 117 - Make sure OD 2.1 & SP 2.2 have the same policy title #303
- [x] Comment 119 - 2.4 Policy bullet should be updated to "should be set to 30 days or less" #300
- [x] Comment 121 - Swap order of 2.1 & 2.2 #303
- [x] Comment 122 - Should 2.2 be broken up into multiple pieces? #302
- [ ] Comment 136 - enable premium audit events (research)
- [x] Comment 160 - Duplicate of comment 136
- [x] Comment 177 - Add policy “Guests might sign in using the same account to which sharing invitations are sent” #307
- [x] Comment 188 - 2.2 Extension of comment 122, Possibly add approved domains and security groups as separate "SHOULD" policies. #302
- [x] Comment 189 - 2.2 More restrictive policies will pass #306
- [x] Comment 190 - 2.3 Should it be removed? #288 
- [x] Comment 191 - Duplicate of comment 119 #300
- [x] Comment 192 - 2.4 add details on the re authentication process for agency awareness #299

**Comment by Sloane4** [comment]
recommend this issue be closed as the github issues have been made & assigned @ahuynhMITRE

**Comment by ahuynhMITRE** [comment]
> recommend this issue be closed as the github issues have been made & assigned @ahuynhMITRE

Reviewed and good to go!
