### ISSUE TITLE
Improve Cached Tenant Settings cmdlet support

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#44]
These are my comments on Run-Cached:

- I tested it and no errors. It only works if there is a ProviderSettingsExport.json in the current directory. See my last bullet.
- [x] Rename it to make it unique just like we did for Disconnect-Tenant. FYI - Cassey is referencing Run-Cached in her regression test script. (This may be OBE as regression test script likely replaced by new testing framework.)
This is now done and was renamed `Invoke-ScubaCached` to differentiate it and make it more unique

- [x] When I execute Run-Cached without any parameters, it simply acts like `Invoke-Scuba`. I think we should change the default behavior to distinguish it. Perhaps by default it will set the -ExportProvider $false ?
- [x] Since we are exporting `Invoke-ScubaCached`, do we need to add any instructions to the README? Or do we simply let developers figure this script out by examining the code on their own?
This is now documented in the functional testing README.
- [ ] I think the script should output a friendly message when there is no ProviderSettingsExport.json file in the current directory or in OutPath. Right now the user gets a bunch of generic errors.

_Originally posted by @tkol2022

- [x] Should also be renamed from `Invoke-RunCached` to `Invoke-SCuBACached`

**Comment by crutchfield** [comment]
Is it worth some way of indicating the output was by Invoke-RunCached instead of Invoke-Scuba?  

Looking at the items listed, I recommend the following: 

1. Rename it to make it unique just like we did for Disconnect-Tenant. FYI - Cassey is referencing Run-Cached in her regression test script. (This may be OBE as regression test script likely replaced by new testing framework.) _**I agree rename Invoke-RunCached to Invoke-ScubaRunCached is value added.**_.
2. When I execute Run-Cached without any parameters, it simply acts like Run-Scuba. I think we should change the default behavior to distinguish it. Perhaps by default it will set the -ExportProvider $false ? Good idea.  _**In the functional tests we used ModifiedProviderSettings.json.**_  
3. Since we are exporting Run-Cached, do we need to add any instructions to the README? Or do we simply let developers figure this script out by examining the code on their own?  **_I would not expect the average user to use this function.  So I'd recommend we document in a deve;oper/contributor area instead of main user documentation.  A nefarious user could use to fudge results to report. Otherwise, I would have suggested we just add another (already to many) switch to Invoke-Scuba for calling Invoke-RunCached and not export it._** 
4. I think the script should output a friendly message when there is no ProviderSettingsExport.json file in the current directory or in OutPath. Right now the user gets a bunch of generic errors. _**Agree**_

**Comment by tkol2022** [comment]
I'm removing myself from this for now because it is crowding my to-do list and this is very low priority compared to the plethora of other items we have in our buckets.

**Comment by FollyBeachGurl** [comment]
This issue will stay in the backlog for now and the team will revisit.

**Comment by tkol2022** [comment]
Closing this since we are going to combine Invoke-ScubaCached with Invoke-Scuba and there are no further actions from this issue that are pending.
