### ISSUE TITLE
Provide tenant license information to users

### ISSUE THREAD

**Issue by gdasher** [cisagov/ScubaGear#466]
# Description #

There is value in collecting information around licenses in tenants assessed by Scubagear.  The ScubaGear results should capture licenses aligned to the tenant and potentially other information such as # of seats per license, and # of assigned/unused licenses per license level.  The license information is useful for tenant administrators planning updates based on the baseline assessments to understand any licensing gaps or baseline items that are not addressable at a given license level.

This information can be captured in the AAD provider using existing APIs.  A quick read suggests the [subscribedSkus API](https://learn.microsoft.com/en-us/graph/api/subscribedsku-list?view=graph-rest-1.0&tabs=http) may be the most appropriate.

Steps to completing this epic include:
- Validate which licenses are important to capture and needed via API calls
- Identify how license information is represented in both JSON results
- Collect license information as part of provider assessment JSON results

## Initiative / Goal ##

The goal is to provide ScubaGear users with license information to inform baseline conformance decisions and identify potential license gaps or barriers to implementing secure tenant and service settings.

## Hypothesis ##
Adding license information to the results will aid the user in implementing policies that require specific licenses.  This hypothesis can be measured by user feedback on license features thru pilot interactions.

## Acceptance criteria ##

Criteria that are considered must have for feature launch and in-scope for this epic include:

- [x] Licenses to include have been determined by product owner
- [x] API calls needed to extract license information have been verified as working
- [x] License information JSON format has been agreed upon by devs and product owner
- [x] Provider(s) updated to successfully collect license information and add to JSON results

## Stakeholders / Resources ##
Include CISA decision makers and dev team members in discussions about this epic.  Resources needed for this epic include API access to test tenants to validate ability to acquire license information under different licensing bundles.

## Timeline ##
The current projected timeline for delivery of this epic feature is with the associated release milestone.

## Associated Tasks ##
See the following related issues:

*  #826

**Comment by dagarwal-mitre** [comment]
I have split this epic into subtasks including issue 778, and for Flipper, I will put the data for the licensing information into the JSON for Flipper. After the meeting with CISA, we decided on the specific licensing information relevant for ScubaGear.
