### ISSUE TITLE
Publish ScubaGear versions to public package repository

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#645]
# Description #

This epic is a larger feature to enable easier distribution of the ScubaGear tool.  This is primarily for the M365 administrator or ScubaGear user that wishes to use the tool.  The work is to investigate alternative means of packaging and publishing the ScubaGear tool in a way that makes it more easily accessible to those users.

ScubaGear is currently distributed via the GitHub release as a zip file.  This requires users to run through a semi-automated installation process.  Since ScubaGear is a combination of PowerShell and Rego code, the installation process could be made easier and more readily available to users through existing package management tools.  For PowerShell, this would be done through the public package repository, [PowerShell Gallery](https://www.powershellgallery.com).  This would provide a commonly understood mechanism for PowerShell users to install ScubaGear without following custom instructions and decrease overall friction to install and use ScubaGear.

Steps to completing this epic include:
- Verify how PSGallery packaging works and what parts of ScubaGear can and cannot be packaged this way
- Determine what a new install process would be with ScubaGear in PSGallery
- Build a test PSGallery account to test creating a PSGallery published ScubaGear module
- Create a production PSGallery account for publishing ScubaGear
- Generate the production PSGallery package for ScubaGear and publish it

## Initiative / Goal ##

The goal is to make ScubaGear more readily accessible through the existing Microsoft PowerShell gallery public package repository and installable through the `Install-Module` cmdlet.  This will make it easier to get ScubaGear into the hands of M365 administrators and users that wish to assess their M365 tenants.

## Hypothesis ##
By making ScubaGear more readily available to the public in an easily retrievable form, the tool will be used more broadly and users will have fewer issues installing it.  This can be measured by tracking downloads of the module from PSGallery versus downloads of the GitHub release package.  Also, the team can track the number of reported issues with the installation process relative to the PSGallery version and a direct install.

## Acceptance criteria ##

Criteria that are considered must have for feature launch and in-scope for this epic include:

- [x] ScubaGear modules have been published to a test PSGallery account successfully
- [x] ScubaGear modules have been published to a production PSGallery account successfully
- [x] A user can successfully install and run ScubaGear using `Install-Module` and PSGallery

## Stakeholders / Resources ##
Include CISA decision makers and dev team members in discussions about this epic.  Resources needed for this epic include access to a code signing certificate and one or more PSGallery accounts.

## Timeline ##
The current projected timeline for delivery of this epic feature is with the associated release milestone.

## Associated Tasks ##
See details on publishing to PSGallery in #94 
* [x] #672 => #673, #674, #675, #678 (test package repo)
* [x] #677  => #678, #679, #680, #681 (refactor ScubaGear module)
* [x] #837

**Comment by tkol2022** [comment]
@schrolla @nanda-katikaneni @james-garriss  Based on our meeting with Crutch yesterday, here are some follow-up action items, if someone can take them, I would appreciate it. Copying @mitchelbaker-cisa and @gdasher FYSA.

1. Reserve time at the end of the current release to perform manual testing of ScubaGear installation/execution once it is published to the PSGallery. 
2. Assign someone to do some preliminary testing now with a pre-release version of the tool. Assign someone to do the testing against the release version.
3. Create GitHub issues to revise the README file to reflect the new way of installing ScubaGear from the PSGallery. I think we need to meet and decide on whether to keep some instructions for users that need to install manually from GitHub. I recommend that this change to the README occur in the next release because I don't want to rush it.

Feel free to add actions that are needed.
