### ISSUE TITLE
OPA Rego engine, style, and functional updates

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#648]
# Description #

This epic is a larger feature to update style and functional use of the OPA Rego language in ScubaGear.  This is primarily for the ScubaGear developer to ease maintenance and the ScubaGear user to ensure they are using up to date software.  The work is to make sure ScubaGear operates with the latest version of the OPA Rego engine and conforms with language "strict mode" requirements.

ScubaGear relies on the OPA Rego engine to assess M365 tenant configurations.  ScubaGear still uses an older version, 0.42.x, version of the OPA engine and several updates to the engine have occurred since.  In addition, style and best practice guidance for the Rego language has also evolved over the last year.  

Steps to completing this epic include:
- Determine all ScubaGear code that causes errors or flags when running Rego engine in strict mode
- Update ScubaGear Rego code to comply with style guidance and strict mode conventions
- Update ScubaGear to automatically download updated version(s) of the OPA engine as part of installation
- Develop a more complete set of Regal style checks for use in Rego linting during development
- Enforce additional Rego linting checks as part of automated development pipeline

## Initiative / Goal ##

The goal is to make ScubaGear more secure by using the latest OPA engine version available without impacting the M365 assessment results.  Secondarily, the goal is to improve overall Rego code quality and maintainability through adherence to best practice conventions and specific style guidelines to ensure consistency across the code base.

## Hypothesis ##
Adherence to a common style format and updating ScubaGear Rego code to adhere to OPA strict mode conventions will make the code easier to maintain over time and support operation with the latest versions of the engine.  Making updates to the code and confirming that it operates as intended with the latest version of the OPA engine can validate this hypothesis.

## Acceptance criteria ##

Criteria that are considered must have for feature launch and in-scope for this epic include:

- [x] Identified all ScubaGear code that results in strict mode errors in current code base
- [x] Updated ScubaGear Rego code to comply strict mode conventions such that no errors are returned on evaluation
- [x] ScubaGear installation scripts are updated to securely retrieve an up-to-date version of the OPA engine
- [x] Updated Regal configuration with additional style conventions is successfully merged into the ScubaGear repository
- [x] Additional Rego linting checks are enforced and reported as part of automated development pipeline

## Stakeholders / Resources ##
Include CISA decision makers and dev team members in discussions about this epic.  Resources needed for this epic include access to the latest versions of the OPA engine.

## Timeline ##
The current projected timeline for delivery of this epic feature is with the associated release milestone.

## Associated Tasks ##
See the following related issues:

- [x] Rego Code Refactoring #632 #633 #634 #635 #636 #637 #638 
- [x] Regal Linting rules update #615 
- [x] Support update to latest OPA engine #195 #196 #593

**Comment by mitchelbaker-cisa** [comment]
Adding this issue as well for relevance: #593
