### ISSUE TITLE
Refine development process

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#665]
# Description #

This epic is a larger feature to continue evolving the ScubaGear development process.  This is primarily for the ScubaGear developer working on updating software.  The work is to investigate changes to process and tooling that supports how developers plan and execute user stories and implement changes to the code.  While the development process itself will be in a continual state of update and maintenance, this epic focuses on creating a solid foundation.

Steps to completing this epic include:
- Adding and refining project specific issue templates aligned to the development process
- Identifying additional automated actions for inclusion in the development pipeline
- Implementing changes to the development pipeline to improve developer efficiency and code quality

## Initiative / Goal ##

The goal is to create a base development process, supported by a corresponding automated pipeline, to reduce friction in the process to convert user stories into executable code.

## Hypothesis ##
By making the development process more efficient, updates to ScubaGear can be made and published to users more quickly and with a higher level of quality.  This hypothesis can be tested by measuring the velocity of releases and issues in those releases along with the number of bugs reported after a release.

## Acceptance criteria ##

Criteria that are considered must have for feature launch and in-scope for this epic include:

- [x] Development pipeline changes and additions have been identified and added to the epic (see associated tasks)
- [x] Development pipeline has been successfully updated with identified changes to support development process

## Stakeholders / Resources ##
Include CISA decision makers and dev team members in discussions about this epic.  Resources needed for this epic include access to GitHub actions marketplace and ability to create new issue templates.

## Timeline ##
The current projected timeline for delivery of this epic feature is with the associated release milestone.

## Associated Tasks ##
See details in the following issues:

- [x] Resolve #57
- [x] Add capability with #700 
- [x] Support additional functional testing via #652
- [x] Clean up testing with #759 
- [x] Further pipeline refinement with #669 
- [x] #731

**Comment by james-garriss** [comment]
Looking at Mega-Linter as a possible lint tool.

**Comment by james-garriss** [comment]
Looking at Application Inspector as a potential static analysis code checker.
