### ISSUE TITLE
Publish ScubaGear to test package repository

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#672]
# 💡 Summary #

PowerShell Gallery is [not designed to testing the publishing process](https://learn.microsoft.com/en-us/powershell/gallery/concepts/publishing-guidelines?view=powershellget-2.x#test-using-a-local-repository).  We need to establish a local repository to test publishing ScubaGear. 

## Motivation and context ##

Why does this work belong in this project?

This would be useful because it supports #645 to 'Publish ScubaGear' versions to a public package repository.  

## Implementation notes ##

Reference #94, #645 for conext and additional information. 

- [X] Add authentication support (i.e., secret - access token (classic) for authenticating to GitHub Packages) for GitHub Actions workflow #673 - Issue closed due to GitHub only supporting v3 of nuget repo and requiring PowerShell v6+. Using local file system repo for test repo. 
- [X] Catalog sign ScubaGear using test code signing certificate #674 - PR #699
- [X] Publish ScubaGear to test repository using PowerShellGet #675 - PR #699
- [X] Test/validate published ScubaGear module #676 - PR #699

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Properly signed ScubaGear module is automatically pushished to test repository on merge
- [ ] Published ScubaGear is automatically tested (e.g., Install-Module, Find-Module, Uninstall-Module,...)

**Comment by crutchfield** [comment]
Closed with #699
