### ISSUE TITLE
Code signing redesign

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#693]
# Description #

This epic is a larger feature to redesign and redevelop the project release code signing automation.  This is primarily for the ScubaGear developers and release managers, but also supports users since running signed code allows the tool to function better on systems where unsigned code is prohibited or produces extra warnings.  The work is to investigate changes to code signing process to support requesting cryptographic operations from a hardware security module and associated implementations changes to continue supporting an automated code signing action as part of the release process.

Steps to completing this epic include:
- Identifying a specific hardware security module or cryptographic vault for storing the project private key
- Generating a new private key in the HSM
- Enabling permissions for programmatic access to the HSM that allows for code signing operations
- Securely loading HSM access credentials into GitHub for use by code signing action
- Updating the code signing GitHub action to use the new HSM key for signing operations
- Implementing changes to the development pipeline to use new code signing action

## Initiative / Goal ##

The goal is to continue to perform Authenticode signing of PowerShell modules in ScubaGear using a new certificate associated with a hardware protected private key.  Signing will be done using automation to support rapid, on-demand publishing of new signed ScubaGear releases.

## Hypothesis ##
By updating the code signing process to support hardware modules, ScubaGear can continue to provide signed releases that are easier to install on secure workstations that prohibit running unsigned PowerShell scripts. 

## Acceptance criteria ##

Criteria that are considered must have for feature launch and in-scope for this epic include:

- [x] New HSM or cryptographic vault has been identified for use
- [x] A new private key has been successfully generated within the identified hardware module
- [x] An HSM credential that allows for signing operations with the new private key has been created and made available to ScubaGear repository administrators
- [x] A new certificate signing request (CSR) has been generated with the new key and sent to the public CA registrar along with a signed letter attesting to the key meeting protection requirements
- [x] The code signing certificate has been successfully signed and issued by the CA registrar and provided to ScubaGear admins
- [x] The new HSM credential and certificate have been loaded into secure storage for use by GitHub action automation
- [x] The existing GitHub code signing and release workflow has been updated to use the new key and certificate
- [x] Development pipeline has been successfully updated with identified changes to support release code signing process

## Stakeholders / Resources ##
Include CISA decision makers and dev team members in discussions about this epic.  Resources needed for this epic include access to GitHub actions, an identified HSM resource to store the private key, and credentials to request signing on-demand.

## Timeline ##
The current projected timeline for delivery of this epic feature is with the associated release milestone.

## Associated Tasks ##
See details in the following issues:

* #710
