### ISSUE TITLE
Automatic dependency update testing

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#698]
# 💡 Summary #

Create an automated capability integrated with the repository to check for updated versions of dependencies and run ScubaGear with them, providing a report of the output and whether ScubaGear ran successfully with the new version(s).  This action should notify developers of updates and the results of the testing when completed.

## Motivation and context ##

ScubaGear relies on a number of third-party PowerShell libraries and the OPA rego engine.  Updates to these libraries and tools may impact the ability of ScubaGear to run in user environments using these new versions that are desirable due to security fixes or enhancements.  Tracking these updates manually is tedious and time-consuming along with the testing that comes with it.  Having an automated service that monitors for updates and tests them when found would narrow the window of time for developers to become aware of updates and decrease time to verify if these new versions are compatible.

## Implementation notes ##

Please provide details for implementation, such as:

- Investigate GitHub dependabot service to monitor and test updates 
- Identify other possible dependency bot-like capabilities if dependabot does not support rego/PowerShell 
- Implement bot in GitHub action for testing
- Validate action for OPA rego engine update and PowerShell library update
- Integrate new action into development pipeline on a schedule

Implementation Issues:
- #1003
- #1096

## Acceptance criteria ##

How do we know when this work is done?

- [x] Candidate dependency services/automation have been successfully identified
- [x] Review and testing of candidate solutions successfully completed
- [x] GitHub action that runs on a schedule implemented to monitor ScubaGear depedencies
- [x] New GitHub action has been successfully tested and validated
- [x] GitHub action integrated into main branch development pipeline
