### ISSUE TITLE
Dev process improvements

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#819]
# Description #

This epic is a larger feature to continue evolving the ScubaGear development process.  This is primarily for the ScubaGear developer working on updating software.  The work is to investigate changes to process and tooling that supports how developers plan and execute user stories and implement changes to the code.  While the development process itself will be in a continual state of update and maintenance, this epic focuses on creating a solid foundation.

Steps to completing this epic include:
- Adding and refining project specific documentation aligned to the development process
- Identifying additional automated actions for inclusion in the development pipeline
- Implementing changes to the development pipeline to improve developer efficiency and code quality

## Initiative / Goal ##

The goal is to create a base development process, supported by a corresponding automated pipeline, to reduce friction in the process to convert user stories into executable code.

## Hypothesis ##
By making the development process more efficient, updates to ScubaGear can be made and published to users more quickly and with a higher level of quality.  This hypothesis can be tested by measuring the velocity of releases and issues in those releases along with the number of bugs reported after a release.

## Acceptance criteria ##

Criteria that are considered must have for feature launch and in-scope for this epic include:

- [x] The project contains dev process documentation to make contributing and releases easier
- [x] Nightly functional testing is expanded to run for all supported M365 products against at least one tenant
- [x] Discrete GitHub actions and workflows are integrated into a pipeline

## Stakeholders / Resources ##
Include CISA decision makers and dev team members in discussions about this epic.  Resources needed for this epic include access to GitHub actions marketplace and ability to create new issue templates.

## Timeline ##
The current projected timeline for delivery of this epic feature is with the associated release milestone.

## Associated Tasks ##
See details in the following issues:

- [x] #56 
- [x] #805
- [x] #840 
- [x] #859 
- [x] #824 
- [x] #846 
- [x] #825 
- [x] #995
