### ISSUE TITLE
HTML reporting improvements

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#820]
# Description #

This epic focuses on making user interface improvements to ScubaGear HTML reports.  The current reports contain mostly static HTML and CSS elements with basic styling. 

Improvements for this epic include:
- Improving accessibility of current reports for broad usability
- Adding additional information to reports useful to tenant administrators
- Refining the current look and feel of the reports

## Initiative / Goal ##

The goal is to make the HTML reporting easier for users to read, provide more information for decision making, and improve the look and feel of the reports.

## Hypothesis ##
By making the ScubaGear reporting easier to read and use, tenant administrators will be able to use reporting guidance to help adjust tenant settings helping to ensure a more secure SaaS environment for users.

## Acceptance criteria ##

Criteria that are considered must have for feature launch and in-scope for this epic include:

- [x] The HTML reports have been reviewed for 508 compliance and new issues added to epic as needed
- [x] New tests have been built to validate HTML report changes work/look as intended
- [x] Run through the report with a screen reader, https://www.nvaccess.org/download/

## Stakeholders / Resources ##
Include CISA decision makers and dev team members in discussions about this epic.  Resources needed for this epic include access to GitHub actions marketplace and ability to create new issue templates.

## Timeline ##
The current projected timeline for delivery of this epic feature is with the associated release milestone.

## Associated Tasks ##
See details in the following issues:

- [x] #93
- [x] #778 
- [x] #175
