### ISSUE TITLE
Add feature to allow users to auto remediate failed policies

### ISSUE THREAD

**Issue by crutchfield** [cisagov/ScubaGear#909]
# 💡 Summary #

This feature would allow a subset of policies to be auto remediated by ScubaGear.

## Motivation and context ##

This would be useful because it would allow the user to more efficiently secure the tenant.  

## Implementation notes ##

Not all policies are easily automatically remediated.  The user may or may not even desire to use auto-remediation. 
- Allow user to choose to activate auto-remediation on a per policy basis.
- Allow user to choose to active auto-remediation on a per product basis.
- Allow user to choose to activate auto-remediation for all products.
- Report if a policy has been auto-remediated

## Acceptance criteria ##

How do we know when this work is done?

- [ ] All policies are annotated if they support auto-remediation
- [ ] User can indicate which policies, products or all will be auto-remediated. 
- [ ] Applicable policies are auto-remediated upon request.

**Comment by tkol2022** [comment]
@adhilto Can you please take a look at this old issue? I feel like we might have addressed this with the omitted policies feature or other recent similar enhancements? If this is OBE, please close it with a note.

**Comment by adhilto** [comment]
This is unrelated to any recent enhancements. The question here is, should ScubaGear be a read-only tool, or could it also have the capability to change settings? The direction we have consistently taken is that ScubaGear should be read-only. I don't expect that direction to change any time soon so I think we can close this as not-planned.
